In [1]:
list = [1, 2, 3, 5, 7, 11, 13]

In [2]:
print(list)

[1, 2, 3, 5, 7, 11, 13]


In [5]:
list2 = [2, 4, 6 ,8, 10, 12, 14]

In [6]:
print(list2)  

[2, 4, 6, 8, 10, 12, 14]


In [7]:
matrix = [list, list2]

In [8]:
print(matrix)

[[1, 2, 3, 5, 7, 11, 13], [2, 4, 6, 8, 10, 12, 14]]


In [4]:
 vector = [1, 2, 3]

In [10]:
print(type(vector))

<class 'list'>


In [3]:
import numpy as np

In [5]:
nvector = np.array(vector)

In [6]:
nvector

array([1, 2, 3])

In [7]:
np.resize(nvector, (4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [8]:
nvector.resize((3, 3), refcheck= False)

In [9]:
nvector

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
matrix = np.ones((4, 4))

In [12]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
matrix = np.zeros((4, 4))

In [14]:
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
matrix2 = np.diag(matrix)

In [21]:
matrix2

array([1., 1., 1., 1.])

In [22]:
np.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [24]:
matrix = np.zeros((4, 4), int)

In [25]:
matrix

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
m1 = np.zeros((3, 5), int)

In [27]:
m1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
m2 = np.ones((3, 5), int)

In [30]:
np.vstack([m2, m1])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
np.hstack([m1, m2])

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]])

In [32]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [33]:
z = x + y
z

array([5, 7, 9])