In [1]:
list = [1, 2, 3, 5, 7, 11, 13]

In [2]:
print(list)

[1, 2, 3, 5, 7, 11, 13]


In [5]:
list2 = [2, 4, 6 ,8, 10, 12, 14]

In [6]:
print(list2)  

[2, 4, 6, 8, 10, 12, 14]


In [7]:
matrix = [list, list2]

In [8]:
print(matrix)

[[1, 2, 3, 5, 7, 11, 13], [2, 4, 6, 8, 10, 12, 14]]


In [2]:
 vector = [1, 2, 3]

In [10]:
print(type(vector))

<class 'list'>


In [4]:
import numpy as np

In [5]:
nvector = np.array(vector)

In [6]:
nvector

array([1, 2, 3])

In [7]:
np.resize(nvector, (4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [7]:
nvector.resize((3, 3), refcheck= False)

In [8]:
nvector

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
matrix = np.ones((4, 4))

In [12]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
matrix = np.zeros((4, 4))

In [14]:
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
matrix2 = np.diag(matrix)

In [21]:
matrix2

array([1., 1., 1., 1.])

In [22]:
np.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [24]:
matrix = np.zeros((4, 4), int)

In [25]:
matrix

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
m1 = np.zeros((3, 5), int)

In [27]:
m1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
m2 = np.ones((3, 5), int)

In [30]:
np.vstack([m2, m1])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
np.hstack([m1, m2])

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]])

In [32]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [33]:
z = x + y
z

array([5, 7, 9])

In [37]:
nvector

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
nvector.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [39]:
nvector.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [40]:
nvector.sum()

6

In [42]:
nvector.max()

3

In [43]:
nvector.min()

0

In [44]:
nvector.argmax()

2

In [45]:
nvector.argmin()

3

In [46]:
nvector.mean()

0.6666666666666666

In [47]:
nvector.std()

1.0540925533894598

In [55]:
mr = np.arange(15) ** 2

In [56]:
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [57]:
mr[2]

4

In [58]:
mr[1:5]

array([ 1,  4,  9, 16])

In [59]:
mr[-1]

196

In [60]:
mr[14]

196

In [61]:
mr[:10]

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [63]:
mr[2:-2]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [64]:
mr[2:-2:2]

array([  4,  16,  36,  64, 100, 144])

In [9]:
nvector

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
nvector[0]

array([1, 2, 3])

In [11]:
nvector[0:2]

array([[1, 2, 3],
       [0, 0, 0]])

In [12]:
nvector[0:2, 1:3]

array([[2, 3],
       [0, 0]])